name: ChimCanhVIP
version: '1.0.0'
main: vn.been.chimcanh.ChimCanhVIP
api-version: '1.21'
authors: [Been]
description: Hệ thống nuôi chim cảnh và thách đấu.
depend: [Vault]

commands:
  chimcanh:
    description: Lệnh chính của ChimCanhVIP.
    aliases: [chim, cc]